vehicles:
  A:
    locator:
      hue:
        item1: 100
        item2: 150
      saturation:
        item1: 100
        item2: 255
      value:
        item1: 100
        item2: 255
      minArea: 4
    showMask: false
    serialPort: COM16
    baudrate: 115200
  B:
    locator:
      hue:
        item1: 0
        item2: 50
      saturation:
        item1: 120
        item2: 255
      value:
        item1: 100
        item2: 255
      minArea: 4
    showMask: false
    serialPort: ''
    baudrate: 115200
camera: 1
